### ISSUE TITLE
JEI display wrong anvil recipe .

### ISSUE THREAD

**Issue by CKenJa** [TeamMFR/MineFantasy-reborn#38] opened 2022-03-08 14:28 UTC
JEI sometimes displays the wrong anvil recipe.
The correct recipe can be found in the book.
The following are currently confirmed
- blast furnace chamber
- blast furnace heater
- iron frame

**Comment by ThatPolishKid99** [comment] 2022-03-08 14:29
Duplicate of #16

**Closed as completed by ThatPolishKid99** 2022-03-08 14:29 UTC
