### ISSUE TITLE
Jei Iron Frame Recipe Error

### ISSUE THREAD

**Issue by CCCClear** [TeamMFR/MineFantasy-reborn#44] opened 2022-05-11 16:23 UTC
I found that the iron frame jei recipe was wrong in the game, but of course it didn't affect the play very much.
I'm just wondering why, as far as I know there is no recipe written specifically for Jei
![frame](https://user-images.githubusercontent.com/44665051/167899233-79df6ddc-16b9-49bd-bd6e-3bc68ccd18ca.png)
.

**Comment by ThatPolishKid99** [comment] 2022-05-11 16:24
Duplicate of #16

**Closed as completed by ThatPolishKid99** 2022-05-11 16:24 UTC
